/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWebhooksIndexRouteImport } from './routes/dashboard/webhooks/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardKeysIndexRouteImport } from './routes/dashboard/keys/index'
import { Route as DashboardBillingIndexRouteImport } from './routes/dashboard/billing/index'
import { Route as DashboardAuditIndexRouteImport } from './routes/dashboard/audit/index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects/$projectId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebhooksIndexRoute = DashboardWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysIndexRoute = DashboardKeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingIndexRoute = DashboardBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditIndexRoute = DashboardAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/audit/': typeof DashboardAuditIndexRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/keys/': typeof DashboardKeysIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/webhooks/': typeof DashboardWebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/audit': typeof DashboardAuditIndexRoute
  '/dashboard/billing': typeof DashboardBillingIndexRoute
  '/dashboard/keys': typeof DashboardKeysIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/webhooks': typeof DashboardWebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/audit/': typeof DashboardAuditIndexRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/keys/': typeof DashboardKeysIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/webhooks/': typeof DashboardWebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/audit/'
    | '/dashboard/billing/'
    | '/dashboard/keys/'
    | '/dashboard/projects/'
    | '/dashboard/webhooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/projects/$projectId'
    | '/dashboard/audit'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/projects'
    | '/dashboard/webhooks'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/audit/'
    | '/dashboard/billing/'
    | '/dashboard/keys/'
    | '/dashboard/projects/'
    | '/dashboard/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/webhooks/': {
      id: '/dashboard/webhooks/'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks/'
      preLoaderRoute: typeof DashboardWebhooksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys/': {
      id: '/dashboard/keys/'
      path: '/keys'
      fullPath: '/dashboard/keys/'
      preLoaderRoute: typeof DashboardKeysIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing/': {
      id: '/dashboard/billing/'
      path: '/billing'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof DashboardBillingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit/': {
      id: '/dashboard/audit/'
      path: '/audit'
      fullPath: '/dashboard/audit/'
      preLoaderRoute: typeof DashboardAuditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardAuditIndexRoute: typeof DashboardAuditIndexRoute
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute
  DashboardKeysIndexRoute: typeof DashboardKeysIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardWebhooksIndexRoute: typeof DashboardWebhooksIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardAuditIndexRoute: DashboardAuditIndexRoute,
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
  DashboardKeysIndexRoute: DashboardKeysIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardWebhooksIndexRoute: DashboardWebhooksIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
